//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendevarimproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bagisekle
    {
        public int id { get; set; }
        public string bagisadi { get; set; }
        public string aciklama { get; set; }
        public int miktar { get; set; }
        public string bagisfotograf { get; set; }
    }
}
