//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendevarimproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projedenemeEntities : DbContext
    {
        public projedenemeEntities()
            : base("name=projedenemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bagis> bagis { get; set; }
        public virtual DbSet<bridge> bridge { get; set; }
        public virtual DbSet<bridgeb> bridgeb { get; set; }
        public virtual DbSet<etiket> etiket { get; set; }
        public virtual DbSet<istek> istek { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<parabagisistek> parabagisistek { get; set; }
        public virtual DbSet<onaylananparabagisi> onaylananparabagisi { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
        public virtual DbSet<bagisekle> bagisekle { get; set; }
        public virtual DbSet<bagisyap> bagisyap { get; set; }
    }
}
